//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ngStudent
    {
        public int id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string contactpreference { get; set; }
        public System.DateTime birthdate { get; set; }
        public int departmentid { get; set; }
        public bool isactive { get; set; }
        public string photopath { get; set; }
    }
}
